function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 26-Apr-2018 14:25:50

% Create figure
figure1 = figure('PaperType','<custom>','PaperSize',[35 12],...
    'PaperUnits','centimeters',...
    'InvertHardcopy','off',...
    'Color',[1 1 1]);

% Create axes
Datas = min(X1):365:max(X1);
Anos = datestr(Datas);
axes1 = axes('Parent',figure1,...
    'XTickLabel',Anos,...
    'XTick',Datas,...
    'FontSize',12);

%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[min(X1) max(X1)]);

%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 450]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'Color','r','LineWidth',1.75,'LineStyle','--','DisplayName','SPEA-II');
set(plot1(2),'Color','m','LineWidth',1.75,'LineStyle','-','DisplayName','NSGA-II');
set(plot1(3),'Color','k','LineWidth',1.75,'LineStyle','--','DisplayName','NSGA-III');
set(plot1(4),'Color','b','LineWidth',2,'DisplayName','Observed');
% Create xlabel
xlabel('Time(day)','FontSize',12,'FontName','times');

% Create ylabel
ylabel('Flow(m^3/s)','FontSize',12,'FontName','times');

% Create title
%title('Hidrograma da menor distancia','FontSize',12,'FontName','times');

% Create legend
legend(axes1,'show');

