function createfigureM(X1, YMatrix1)
%CREATEFIGURE1(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 26-Apr-2018 14:47:13

% Create figure
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);

% Create axes
Datas = min(X1):365:max(X1);
Anos = datestr(Datas);
axes1 = axes('Parent',figure1,...
    'XTickLabel',Anos,...
    'XTick',Datas,...
    'FontSize',12);
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[min(X1) max(X1)]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'Color',[0 0 0]);
set(plot1(1),'Color',[0 0 1],'DisplayName','Hydrograph Observed');
set(plot1(2),'DisplayName','Hydrographs Calculated');

% Create xlabel
xlabel('Time(day)','FontSize',12,'FontName','times');
% Create ylabel
ylabel('Flow(m^3/s)','FontSize',12,'FontName','times');

% Create title
%title('Calculated Hydrographs of non-dominated solutions','FontSize',12,'FontName','times');
% Create legend
legend1 = legend('Observed','Calculated');
set(legend1,...
    'Position',[0.649156939040207 0.734214390602055 0.218871595330739 0.101321585903084]);

